name: build-all-containers

on:
  push:
    branches:
      - "master"

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: php74
            folder: php/7.4
            arch: [linux/amd64, linux/arm64, linux/arm64/v8]
            targets:
              primary: cli
              secondary: fpm
              tertiary: swoole

#          - name: php80
#            folder: php/8.0
#            arch: [linux/amd64, linux/arm64]
#            targets:
#              primary: cli
#              secondary: fpm
#              tertiary: swoole

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push primary container
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.folder }}
          platforms: ${{ join(matrix.arch, ',') }}
          push: true
          pull: true
          tags: shirokikh/${{ format('{0}-{1}', matrix.name, matrix.targets.primary) }}:latest
          target: ${{ matrix.targets.primary }}
#          cache-from: type=registry,ref=shirokikh/${{ matrix.targets.primary && format('{0}-{1}', matrix.name, matrix.targets.primary) || matrix.name }}:buildcache
#          cache-to: type=registry,ref=shirokikh/${{ matrix.targets.primary && format('{0}-{1}', matrix.name, matrix.targets.primary) || matrix.name }}:buildcache,mode=max

#      - name: Build and push secondary container
#        if: matrix.targets.secondary
#        uses: docker/build-push-action@v2
#        with:
#          context: ${{ matrix.folder }}
#          platforms: ${{ join(matrix.arch, ',') }}
#          push: true
#          pull: true
#          tags: shirokikh/${{ format('{0}-{1}', matrix.name, matrix.targets.secondary) }}:latest
#          target: ${{ matrix.targets.secondary }}
#          cache-from: type=registry,ref=shirokikh/${{ format('{0}-{1}', matrix.name, matrix.targets.secondary) }}:buildcache
#          cache-to: type=registry,ref=shirokikh/${{ format('{0}-{1}', matrix.name, matrix.targets.secondary) }}:buildcache,mode=max

#      - name: Build and push tertiary container
#        if: matrix.targets.tertiary
#        uses: docker/build-push-action@v2
#        with:
#          context: ${{ matrix.folder }}
#          platforms: ${{ join(matrix.arch, ',') }}
#          push: true
#          pull: true
#          tags: shirokikh/${{ format('{0}-{1}', matrix.name, matrix.targets.tertiary) }}:latest
#          target: ${{ matrix.targets.tertiary }}
#          cache-from: type=registry,ref=shirokikh/${{ format('{0}-{1}', matrix.name, matrix.targets.tertiary) }}:buildcache
#          cache-to: type=registry,ref=shirokikh/${{ format('{0}-{1}', matrix.name, matrix.targets.tertiary) }}:buildcache,mode=max
